export default function Cream() {
    document.documentElement.style.setProperty("--text-color", "#CEAB93")
    document.documentElement.style.setProperty("--bg-color", "#FFFBE9")
    document.documentElement.style.setProperty("--border-color", "none")
    document.documentElement.style.setProperty("--note-color", "#FFEEEE")
    document.documentElement.style.setProperty("--title-color", "#AD8B73")
    document.documentElement.style.setProperty("--icon-color", "#CEAB93")
    document.documentElement.style.setProperty("--icon-shadow-color", "#AD8B73")
    document.documentElement.style.setProperty("--title-shadow", "none")
    document.documentElement.style.setProperty("--note-text-color", "#AD8B73")
    document.documentElement.style.setProperty("--note-date-color", "#CEAB93")
    document.documentElement.style.setProperty("--theme-bg", "#0b001b")
    document.documentElement.style.setProperty("--font-family", "Nunito, sans-serif")
    document.documentElement.style.setProperty("--border-radius", "10px")
    document.documentElement.style.setProperty("--note-shadow", "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px")
}