export default function Light() {
    document.documentElement.style.setProperty("--text-color", "#000")
    document.documentElement.style.setProperty("--bg-color", "#fff")
    document.documentElement.style.setProperty("--border-color", "")
    document.documentElement.style.setProperty("--note-color", "#FFD384")
    document.documentElement.style.setProperty("--title-color", "#000")
    document.documentElement.style.setProperty("--icon-color", "#333333")
    document.documentElement.style.setProperty("--icon-shadow-color", "#000")
    document.documentElement.style.setProperty("--title-shadow", "none")
    document.documentElement.style.setProperty("--note-text-color", "#000")
    document.documentElement.style.setProperty("--note-date-color", "#545c84")
    document.documentElement.style.setProperty("--theme-bg", "#0b001b")
    document.documentElement.style.setProperty("--font-family", "Comfortaa, cursive")
    document.documentElement.style.setProperty("--border-radius", "10px")
    document.documentElement.style.setProperty("--note-shadow", " rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px")
}